version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: front/Dockerfile
    image: clippo-go/front
    container_name: front
    ports:
    - "8080:8080"
    environment:
    - "DBMS=mysql"
    - "PASS=ao6415012"
    - "PROTOCOL=tcp(127.0.0.1:3306)"
    - "DBNAME=clippo"

    # server_cache:
    #   build: ./server_cache
    #   volumes:
    #       - ./:/go/src/server_cache
    #   image: clippo-go/server_cache
    #   ports:
    #       - "50051:50051"
    # server_post:
    #   build: ./server_post
    #   image: clippo-go/server_post
    #   volumes:
    #       - ./:/go/src/server_post
    #   ports:
    #       - "50052:50051"