version: '3'
services:
  front:
    image: 390440882363.dkr.ecr.ap-northeast-1.amazonaws.com/front
    container_name: front
    ports:
    - "80:8080"
    environment:
    - "DBMS=mysql"
    - "PASS=Root0000"
    - "PROTOCOL=clippo-rds.cpciso94q1yy.ap-northeast-1.rds.amazonaws.com"
    - "DBNAME=clippo"
  cache:
    image: 390440882363.dkr.ecr.ap-northeast-1.amazonaws.com/cache
    container_name: cache
    ports:
    - "50051:50051"
  post:
    image: 390440882363.dkr.ecr.ap-northeast-1.amazonaws.com/post
    container_name: post
    ports:
    - "50052:50051"
  user:
    image: 390440882363.dkr.ecr.ap-northeast-1.amazonaws.com/user
    container_name: user
    ports:
    - "50053:50051"