version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: front/Dockerfile
    image: clippo-go/front
    container_name: front
    ports:
    - "9000:8080"
    environment:
    - "DBMS=mysql"
    - "PASS=Root0000"
    - "PROTOCOL=clippo-rds.cpciso94q1yy.ap-northeast-1.rds.amazonaws.com"
    - "DBNAME=clippo"
  cache:
    build:
      context: ./
      dockerfile: cache/Dockerfile
    image: clippo-go/cache
    container_name: cache
    ports:
    - "50051:50051"
  post:
    build:
      context: ./
      dockerfile: post/Dockerfile
    image: clippo-go/post
    container_name: post
    ports:
    - "50052:50051"
  user:
    build:
      context: ./
      dockerfile: user/Dockerfile
    image: clippo-go/user
    container_name: user
    ports:
    - "50053:50051"