version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: front/Dockerfile
    image: clippo-go/front
    container_name: front
    ports:
    - "9000:8080"
    environment:
    - "DBMS=mysql"
    - "PASS=ao6415012"
    - "PROTOCOL=tcp(127.0.0.1:3306)"
    - "DBNAME=clippo"