// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/userpb/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ユーザーの定義
type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type IsUserByEmailExistedRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsUserByEmailExistedRequest) Reset()         { *m = IsUserByEmailExistedRequest{} }
func (m *IsUserByEmailExistedRequest) String() string { return proto.CompactTextString(m) }
func (*IsUserByEmailExistedRequest) ProtoMessage()    {}
func (*IsUserByEmailExistedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{5}
}

func (m *IsUserByEmailExistedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsUserByEmailExistedRequest.Unmarshal(m, b)
}
func (m *IsUserByEmailExistedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsUserByEmailExistedRequest.Marshal(b, m, deterministic)
}
func (m *IsUserByEmailExistedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsUserByEmailExistedRequest.Merge(m, src)
}
func (m *IsUserByEmailExistedRequest) XXX_Size() int {
	return xxx_messageInfo_IsUserByEmailExistedRequest.Size(m)
}
func (m *IsUserByEmailExistedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsUserByEmailExistedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsUserByEmailExistedRequest proto.InternalMessageInfo

func (m *IsUserByEmailExistedRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IsUserByEmailExistedResponse struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsUserByEmailExistedResponse) Reset()         { *m = IsUserByEmailExistedResponse{} }
func (m *IsUserByEmailExistedResponse) String() string { return proto.CompactTextString(m) }
func (*IsUserByEmailExistedResponse) ProtoMessage()    {}
func (*IsUserByEmailExistedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{6}
}

func (m *IsUserByEmailExistedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsUserByEmailExistedResponse.Unmarshal(m, b)
}
func (m *IsUserByEmailExistedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsUserByEmailExistedResponse.Marshal(b, m, deterministic)
}
func (m *IsUserByEmailExistedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsUserByEmailExistedResponse.Merge(m, src)
}
func (m *IsUserByEmailExistedResponse) XXX_Size() int {
	return xxx_messageInfo_IsUserByEmailExistedResponse.Size(m)
}
func (m *IsUserByEmailExistedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsUserByEmailExistedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsUserByEmailExistedResponse proto.InternalMessageInfo

func (m *IsUserByEmailExistedResponse) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "userpb.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "userpb.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "userpb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "userpb.GetUserResponse")
	proto.RegisterType((*IsUserByEmailExistedRequest)(nil), "userpb.IsUserByEmailExistedRequest")
	proto.RegisterType((*IsUserByEmailExistedResponse)(nil), "userpb.IsUserByEmailExistedResponse")
}

func init() { proto.RegisterFile("user/userpb/user.proto", fileDescriptor_9c4d46a2d91a774f) }

var fileDescriptor_9c4d46a2d91a774f = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0xb6, 0xa5, 0xb6, 0x75, 0xa2, 0x15, 0x87, 0x52, 0x63, 0xf4, 0x50, 0x56, 0x11, 0x4f, 0x11,
	0x52, 0x04, 0x0f, 0x9e, 0x5a, 0x82, 0x78, 0x8d, 0x78, 0xf1, 0x96, 0x36, 0x63, 0x09, 0xb4, 0x26,
	0xee, 0xa4, 0x3e, 0x7e, 0xb9, 0x57, 0xd9, 0x4d, 0x36, 0x46, 0x1a, 0xe2, 0x25, 0xd9, 0xd9, 0x99,
	0xef, 0xb1, 0x1f, 0x03, 0xa3, 0x0d, 0x93, 0xbc, 0x56, 0x9f, 0x74, 0xae, 0x7f, 0x6e, 0x2a, 0x93,
	0x2c, 0xc1, 0x6e, 0x7e, 0x25, 0x6e, 0xa1, 0xf3, 0xc4, 0x24, 0x71, 0x08, 0xbb, 0xb4, 0x0e, 0xe3,
	0x95, 0xdd, 0x1a, 0xb7, 0xae, 0xf6, 0x82, 0xbc, 0x40, 0x07, 0xfa, 0x69, 0xc8, 0xfc, 0x91, 0xc8,
	0xc8, 0x6e, 0xeb, 0x46, 0x59, 0x8b, 0x1b, 0x38, 0x9a, 0x49, 0x0a, 0x33, 0x52, 0xf8, 0x80, 0xde,
	0x36, 0xc4, 0x19, 0x8e, 0xa1, 0xa3, 0x88, 0x35, 0x8b, 0xe5, 0xed, 0xbb, 0xb9, 0x8a, 0xab, 0x47,
	0x74, 0x47, 0xb8, 0x80, 0x55, 0x18, 0xa7, 0xc9, 0x2b, 0x13, 0xda, 0xd0, 0x5b, 0x13, 0x73, 0xb8,
	0xa4, 0xc2, 0x80, 0x29, 0xc5, 0x25, 0x0c, 0xee, 0x29, 0xab, 0x6a, 0xd4, 0x5a, 0x15, 0x33, 0x38,
	0x2c, 0xe7, 0x0a, 0xd2, 0x7f, 0xcd, 0xe0, 0x00, 0xda, 0xb1, 0x79, 0x59, 0x3b, 0x8e, 0xc4, 0x04,
	0x4e, 0x1f, 0x58, 0xf5, 0xa7, 0x5f, 0xbe, 0x62, 0xf5, 0x3f, 0x63, 0xce, 0x28, 0x6a, 0x56, 0xf6,
	0xe0, 0xac, 0x1e, 0x54, 0xd8, 0x40, 0xe8, 0xbc, 0xac, 0xc2, 0xa5, 0x06, 0xf5, 0x03, 0x7d, 0xf6,
	0xbe, 0x5b, 0x60, 0x29, 0xc8, 0x23, 0xc9, 0xf7, 0x78, 0x41, 0xe8, 0x03, 0xfc, 0xa6, 0x82, 0x27,
	0xc6, 0xea, 0x56, 0xc0, 0x8e, 0x53, 0xd7, 0xca, 0x85, 0xc4, 0x0e, 0xde, 0x41, 0xaf, 0x08, 0x01,
	0x47, 0x66, 0xf0, 0x6f, 0x7a, 0xce, 0xf1, 0xd6, 0x7d, 0x89, 0x5e, 0xc0, 0xb0, 0xee, 0x21, 0x78,
	0x6e, 0x20, 0x0d, 0xd9, 0x38, 0x17, 0xcd, 0x43, 0x46, 0x64, 0x7a, 0xf0, 0x6c, 0x55, 0x56, 0x72,
	0xde, 0xd5, 0xeb, 0x38, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x86, 0xe6, 0xa0, 0x6a, 0xa8, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	IsUserByEmailExisted(ctx context.Context, in *IsUserByEmailExistedRequest, opts ...grpc.CallOption) (*IsUserByEmailExistedResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsUserByEmailExisted(ctx context.Context, in *IsUserByEmailExistedRequest, opts ...grpc.CallOption) (*IsUserByEmailExistedResponse, error) {
	out := new(IsUserByEmailExistedResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserService/IsUserByEmailExisted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	IsUserByEmailExisted(context.Context, *IsUserByEmailExistedRequest) (*IsUserByEmailExistedResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsUserByEmailExisted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserByEmailExistedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsUserByEmailExisted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/IsUserByEmailExisted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsUserByEmailExisted(ctx, req.(*IsUserByEmailExistedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "IsUserByEmailExisted",
			Handler:    _UserService_IsUserByEmailExisted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/userpb/user.proto",
}
