// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/postpb/post.proto

package postpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostURLRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostURLRequest) Reset()         { *m = PostURLRequest{} }
func (m *PostURLRequest) String() string { return proto.CompactTextString(m) }
func (*PostURLRequest) ProtoMessage()    {}
func (*PostURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8546fe910ba1e09, []int{0}
}

func (m *PostURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostURLRequest.Unmarshal(m, b)
}
func (m *PostURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostURLRequest.Marshal(b, m, deterministic)
}
func (m *PostURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostURLRequest.Merge(m, src)
}
func (m *PostURLRequest) XXX_Size() int {
	return xxx_messageInfo_PostURLRequest.Size(m)
}
func (m *PostURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostURLRequest proto.InternalMessageInfo

func (m *PostURLRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PostResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8546fe910ba1e09, []int{1}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func init() {
	proto.RegisterType((*PostURLRequest)(nil), "postpb.PostURLRequest")
	proto.RegisterType((*PostResponse)(nil), "postpb.PostResponse")
}

func init() { proto.RegisterFile("post/postpb/post.proto", fileDescriptor_a8546fe910ba1e09) }

var fileDescriptor_a8546fe910ba1e09 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0x2f, 0xc8, 0x2f, 0x2e, 0xd1, 0x07, 0x11, 0x05, 0x49, 0x60, 0x4a, 0xaf, 0xa0,
	0x28, 0xbf, 0x24, 0x5f, 0x88, 0x0d, 0x22, 0xa4, 0xa4, 0xc4, 0xc5, 0x17, 0x90, 0x5f, 0x5c, 0x12,
	0x1a, 0xe4, 0x13, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc0, 0xc5, 0x5c, 0x5a, 0x94,
	0x23, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0xe5, 0x71, 0xf1, 0x80, 0xd4, 0x04,
	0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x62, 0xaa, 0x10, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2c,
	0xc9, 0x49, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x42, 0x0a, 0x5c, 0xdc, 0x29, 0xa9, 0xc5, 0xc9,
	0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x12, 0xcc, 0x60, 0x39, 0x64, 0x21, 0x90, 0xbe, 0xcc,
	0xdc, 0xc4, 0xf4, 0x54, 0x09, 0x16, 0x88, 0x3e, 0x30, 0xc7, 0xc8, 0x8f, 0x8b, 0x1b, 0x64, 0x5f,
	0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x3d, 0x17, 0xaf, 0x7b, 0x6a, 0x09, 0x48, 0xc4,
	0x25, 0xb5, 0x24, 0x31, 0x33, 0x47, 0x48, 0x4c, 0x0f, 0xe2, 0x78, 0x3d, 0x54, 0x97, 0x4b, 0x89,
	0x20, 0x8b, 0xc3, 0x5c, 0xab, 0xc4, 0xe0, 0x24, 0x12, 0x25, 0x84, 0x19, 0x18, 0x49, 0x6c, 0xe0,
	0x80, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xba, 0x91, 0x62, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	GetPostDetail(ctx context.Context, in *PostURLRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetPostDetail(ctx context.Context, in *PostURLRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetPostDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	GetPostDetail(context.Context, *PostURLRequest) (*PostResponse, error)
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetPostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetPostDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostDetail(ctx, req.(*PostURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postpb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostDetail",
			Handler:    _PostService_GetPostDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post/postpb/post.proto",
}
